### PR TITLE
Create Navigation Component

### LINKED ISSUE #3: Navigation Component
As a user
i want a navigation
to navigate between the sites

- Create Navigation component
- Insert Icons
- Give it a prop for the active item
- Link it together

### PR DESCRIPTION
**Pull request by ChristianSeelemann**
- I created the Navigation Component
- Not very special things done
- Create a prop to make a specific item active
- Create icon components
- Add color prop to icon components
- Link the items with react-router

Belongs to #3

### CODE REVIEW

**Review by phlgr — CHANGES_REQUESTED** [review]
Nice Work! I would highly recommend removing either the svg files or the svg code from the component and import it from a React Component containing the svg.

**Review by phlgr — CHANGES_REQUESTED** [review]
You don't need a story for every single Icon. Please also add props to the Icon components and pass them to the svg.

**Review by phlgr — APPROVED** [review]
In the case you don't need the props in the Icon this is fine, else please add them. Anyway, Good Job 🎉

**Comment by ChristianSeelemann** [comment]
> In the case you don't need the props in the Icon this is fine, else please add them. Anyway, Good Job 🎉

Already solved :)

**Pull request merged**
